---
title: "Untitled"
author: "Chris Pike"
date: "October 16, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Download Libraries

```{r,warning=F, message=F}
library(dplyr)
library(tidyr)
library(DT)
```

```{r}
catch_df = read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1",method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

`select` the columns we need for analysis
`gather` to move from wide to long
`rename` a column to indicate units
```{r}
catch_clean <- catch_df %>% 
 # select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) # selecting columns to keep
  #selecting columns to get rid of
  select(-All, -notesRegCode) %>% 
  gather(key = "species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)
  
head(catch_clean)
```
```{r}
test <- as.numeric(catch_clean$catch_thousands)
i <-which(is.na(test) == T)
  catch_clean[i, ]
```


`mutate' to create a new catch column
```{r}
catch_clean_mutated <- catch_clean %>% 
  #change I to 1 in catch throusands column
  mutate(catch_thousands = ifelse(catch_thousands =="I", 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands * 1000)

tail(catch_clean_mutated)
```

split using `group_by`
```{r}
catch_sumarized <- catch_clean_mutated %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch))
head(catch_sumarized)
```
#joins
load regions data table

```{r}
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl"),
                        stringsAsFactors = FALSE)
head(region_defs)
```

```{r}
region_defs <- region_defs %>% 
  select(code, mgmtArea)

head(region_defs)
```

```{r}
catch_joined <- left_join(catch_clean_mutated, region_defs, by = c("Region" = "code") )
head(catch_joined)
```

```{r}
dates_df <- data.frame(date = c("5/24/1930",
                                "5/25/1930",
                                "5/26/1930",
                                "5/27/1930",
                                "5/28/1930"),
                       stringsAsFactors = FALSE)
```

```{r}
dates_seperate <- dates_df %>% 
  separate(date, c("month", "day", "year"), "/") %>% 
  unite(col = iso, year, month, day, sep = "-")
  
dates_seperate
```
